goog.require('goog.dom');
goog.require('goog.style');
goog.require('goog.events');
goog.require('goog.ui.Dialog');
goog.require('goog.editor.Table');
goog.require('goog.ui.LabelInput');
goog.require('goog.events.EventType');
goog.require('ru.tomtrix.othello.User')
goog.require('ru.tomtrix.othello.Field')
goog.require('ru.tomtrix.othello.Websocket')
